/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PRINT` (
  `print_id` int(11) NOT NULL AUTO_INCREMENT,
  `negative_id` int(11) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `paper_stock_id` int(11) DEFAULT NULL,
  `height` decimal(4,1) DEFAULT NULL,
  `width` decimal(4,1) DEFAULT NULL,
  `toner_id` int(11) DEFAULT NULL,
  `toner_dilution` varchar(6) DEFAULT NULL,
  `toner_time` time DEFAULT NULL,
  `own` tinyint(1) DEFAULT NULL,
  `location` varchar(45) DEFAULT NULL,
  `enlarger_id` int(11) DEFAULT NULL,
  `lens_id` int(11) DEFAULT NULL,
  `developer_id` int(11) DEFAULT NULL,
  `aperture` decimal(3,1) DEFAULT NULL,
  `exposure_time` decimal(4,1) DEFAULT NULL,
  `development_time` int(11) DEFAULT NULL,
  `filtration_grade` decimal(2,1) DEFAULT NULL,
  `fine` tinyint(1) DEFAULT NULL,
  `notes` text,
  `filename` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`print_id`),
  KEY `fk_PRINT_1` (`paper_stock_id`),
  KEY `fk_PRINT_2` (`negative_id`),
  KEY `fk_PRINT_3` (`toner_id`),
  KEY `fk_PRINT_4` (`enlarger_id`),
  KEY `fk_PRINT_6` (`developer_id`),
  KEY `fk_PRINT_5_idx` (`lens_id`),
  CONSTRAINT `fk_PRINT_1` FOREIGN KEY (`paper_stock_id`) REFERENCES `PAPER_STOCK` (`paper_stock_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_PRINT_2` FOREIGN KEY (`negative_id`) REFERENCES `NEGATIVE` (`negative_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_PRINT_3` FOREIGN KEY (`toner_id`) REFERENCES `TONER` (`toner_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_PRINT_4` FOREIGN KEY (`enlarger_id`) REFERENCES `ENLARGER` (`enlarger_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_PRINT_5` FOREIGN KEY (`lens_id`) REFERENCES `LENS` (`lens_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_PRINT_6` FOREIGN KEY (`developer_id`) REFERENCES `DEVELOPER` (`developer_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=433 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
