#!/usr/bin/perl -wT

# Interactive user interface for interacting with the photography database

use strict;
use warnings;
binmode(STDOUT, ":utf8");
binmode(STDIN, ":encoding(utf8)");

use lib 'lib';
use funcs;
use handlers;
use commands;

# Define handlers for each command
my %handlers = %commands::handlers;

# Read in and verify command
my $command = $ARGV[0] or &nocommand(\%handlers);

# Check if the command is defined in the handlers
if (!exists $handlers{$command}) {
	&nocommand(\%handlers);
}

# Read in and verify subcommand
my $subcommand = $ARGV[1] or &nosubcommand(\%{$handlers{$command}}, $command);
if (!exists $handlers{$command}{$subcommand}) {
	&nosubcommand(\%{$handlers{$command}}, $command);
}

# Connect to the database
my $db = &db;

# Execute chosen handler
$handlers{$command}{$subcommand}{'handler'}->($db);
